server:
  port: 80
spring:
  application:
    name: "bell"
  datasource:
    initialization-mode: always
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:file:./bell-schedule"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
  jackson:
    default-property-inclusion: non_null
  output:
      ansi:
          enabled: detect
  http:
    encoding:
      charset: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: httptrace
logging:
  level:
    root: info
    org.springframework.web: info
  file: "./logs/bell-schedule.log"
  file.max-history: 7
bell:
  schedule:
    jwt:
      secret: "Rl7$u!&0k7Fb"
      expirationInMs: 1800000
