server:
    port: 3000
    servlet:
        context-path: "/bell"
spring:
    application:
        name: "bell"
    datasource:
        initialization-mode: always
        driver-class-name: "org.h2.Driver"
        url: "jdbc:h2:file:./bell-schedule"
    jpa:
        database-platform: "org.hibernate.dialect.H2Dialect"
        hibernate:
            ddl-auto: create
        show-sql: true
    h2:
        console:
            enabled: true
